{% set name = "importlib_metadata" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 073a852570f92da5f744a3472af1b61e28e9f78ccf0c9117658dc32b15de7b45

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - setuptools_scm
    - python
  run:
    - python
    - zipp >=0.5
    - pathlib2  # [py2k]
    - contextlib2  # [py2k]
    - configparser >=3.5  # [py2k]

test:
  imports:
    - importlib_metadata

about:
  home: https://gitlab.com/python-devs/importlib_metadata
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary:  A library to access the metadata for a Python package

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
