{% set version = "4.11.0" %}

package:
  name: importlib-metadata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-{{ version }}.tar.gz
  sha256: 9e5e553bbba1843cb4a00823014b907616be46ee503d2b9ba001d214a8da218f

build:
  number: 0
  # trigger: 1
  skip: True # [py<36]

outputs:
  - name: importlib-metadata
    script: build_base.sh
    requirements:
      host:
        - python
        - pip
        - setuptools >=56
        - setuptools_scm >=3.4.1,!=6.1.0
        - toml
      run:
        - python >=3.6
        - typing_extensions >=3.6.4  # [py<38]
        - zipp >=0.5
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - importlib_metadata

  - name: importlib_metadata
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      imports:
        - importlib_metadata  # [not win32]

about:
  home: https://github.com/python/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package.
  dev_url: https://github.com/python/importlib_metadata
  doc_url: https://importlib-metadata.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
