{% set name = "importlib_metadata" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41e688146d000891f32b1669e8573c57e39e5060e7f5f647aa617cd9a9568278

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - setuptools_scm
    - python
  run:
    - python
    - zipp >=0.5
    - pathlib2  # [py2k]
    - contextlib2  # [py2k]
    - configparser >=3.5  # [py2k]

test:
  imports:
    - importlib_metadata

about:
  home: https://gitlab.com/python-devs/importlib_metadata
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary:  A library to access the metadata for a Python package

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
