{% set name = "importlib_resources" %}
{% set name_alt = name.replace('_', '-') %}
{% set version = "7.0.0" %}

package:
  name: {{ name }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fc841f8b8332803464e5dc1c63a2e59121f46ca186c0e2e182e80bf8c1319f7

build:
  number: 0
  skip: True # [py<38]

outputs:
  - name: {{ name }}
    script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      host:
        - python
        - pip
        - setuptools
        - setuptools_scm >=3.4.1
        - toml
        - wheel
      run:
        - python
        - zipp >=0.5
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - {{ name }}
  - name: {{ name_alt }}
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("importlib_resources", max_pin="x.x.x") }}
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - {{ name_alt }}

about:
  home: https://github.com/python/importlib_metadata
  description: |
    This package supplies third-party access to the functionality of importlib.metadata 
    including improvements added to subsequent Python versions.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package.
  dev_url: https://github.com/python/importlib_metadata
  doc_url: https://importlib-metadata.readthedocs.io

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
