{% set name_norm = "importlib_metadata" %}
{% set name_alt = name_norm.replace('_', '-') %}
{% set version = "8.7.0" %}

package:
  name: {{ name_norm }}-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name_norm[0] }}/{{ name_norm }}/{{ name_norm }}-{{ version }}.tar.gz
  sha256: d13b81ad223b890aa16c5471f2ac3056cf76c5f10f82d6f9292f0b415f389000

build:
  number: 0
  skip: true  # [py<39]

# making this package multi output for the sole purpose of allowing both '-' and '_' naming conventions
outputs:
  - name: {{ name_alt }}
    script: build_base.sh  # [unix]
    script: build_base.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools >=61.2
        - setuptools_scm >=3.4.1
        - toml
      run:
        - python
        - zipp >=3.20
        - typing-extensions >=3.6.4  # [py<38]
    test:
      source_files:
        - tests
      requires:
        - pip
        - pytest
        - jaraco.test >=5.4
        - pyfakefs
      commands:
        - pip check
        - python -c "from importlib.metadata import version; assert(version('{{ name_norm }}')=='{{ version }}')"
        - pytest -v tests
  - name: {{ name_norm }}
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - {{ name_norm }}

about:
  home: https://github.com/python/importlib_metadata
  description: |
    This package supplies third-party access to the functionality of importlib.metadata
    including improvements added to subsequent Python versions.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package.
  dev_url: https://github.com/python/importlib_metadata
  doc_url: https://importlib-metadata.readthedocs.io

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
