{% set version = "6.0.0" %}

package:
  name: importlib-metadata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-{{ version }}.tar.gz
  sha256: e354bedeb60efa6affdcc8ae121b73544a7aa74156d047311948f6d711cd378d

build:
  number: 1
  skip: True # [py<38]

outputs:
  - name: importlib-metadata
    script: build_base.sh  # [unix]
    script: build_base.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - setuptools_scm
        - toml
        - wheel
      run:
        - python
        - typing_extensions >=3.6.4  # [py<38]
        - zipp >=0.5
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - importlib_metadata

  - name: importlib_metadata
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      imports:
        - importlib_metadata

about:
  home: https://github.com/python/importlib_metadata
  description: |
    This package supplies third-party access to the functionality of importlib.metadata 
    including improvements added to subsequent Python versions.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package.
  dev_url: https://github.com/python/importlib_metadata
  doc_url: https://importlib-metadata.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
