{% set name_norm = "importlib_metadata" %}
{% set name_alt = name_norm.replace('_', '-') %}
{% set version = "8.5.0" %}

package:
  name: {{ name_norm }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name_norm[0] }}/{{ name_norm }}/{{ name_norm }}-{{ version }}.tar.gz
  sha256: 71522656f0abace1d072b9e5481a48f07c138e00f079c38c8f883823f9c26bd7

build:
  number: 0
  skip: True # [py<38]

# making this package multi output for the sole purpose of allowing both '-' and '_' naming conventions
outputs:
  - name: {{ name_alt }}
    script: build_base.sh  # [unix]
    script: build_base.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - setuptools_scm >=3.4.1
        - toml
        - wheel
      run:
        - python
        - zipp >=3.20
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: {{ name_norm }}
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - {{ name_norm }}

about:
  home: https://github.com/python/importlib_metadata
  description: |
    This package supplies third-party access to the functionality of importlib.metadata 
    including improvements added to subsequent Python versions.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package.
  dev_url: https://github.com/python/importlib_metadata
  doc_url: https://importlib-metadata.readthedocs.io

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
